# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 0.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.financial_statement_report import FinancialStatementReport

class TestFinancialStatementReport(unittest.TestCase):
    """FinancialStatementReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FinancialStatementReport:
        """Test FinancialStatementReport
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FinancialStatementReport`
        """
        model = FinancialStatementReport()
        if include_optional:
            return FinancialStatementReport(
                items = [
                    openapi_client.models.financial_statement_report_item_entity.FinancialStatementReportItemEntity(
                        type = '', 
                        entries_category_data = openapi_client.models.financial_statemente_entries_category_data.FinancialStatementeEntriesCategoryData(
                            category_id = '', 
                            category_name = '', 
                            outcome = 1.337, 
                            subcategories = [
                                openapi_client.models.financial_statemente_entries_subcategory_data.FinancialStatementeEntriesSubcategoryData(
                                    subcategory_id = '', 
                                    subcategory_name = '', 
                                    outcome = 1.337, )
                                ], ), 
                        outflows_category_data = openapi_client.models.financial_statement_outlfows_category_data.FinancialStatementOutlfowsCategoryData(
                            category_id = '', 
                            category_name = '', 
                            outcome = 1.337, 
                            subcategories = [
                                openapi_client.models.financial_statement_outflows_subcategory_data.FinancialStatementOutflowsSubcategoryData(
                                    subcategory_id = '', 
                                    subcategory_name = '', 
                                    outcome = 1.337, )
                                ], ), 
                        outcome_data = openapi_client.models.financial_statement_outcome_report_data_entity.FinancialStatementOutcomeReportDataEntity(
                            name = '', 
                            outcome = 1.337, 
                            percentage = 1.337, ), )
                    ]
            )
        else:
            return FinancialStatementReport(
                items = [
                    openapi_client.models.financial_statement_report_item_entity.FinancialStatementReportItemEntity(
                        type = '', 
                        entries_category_data = openapi_client.models.financial_statemente_entries_category_data.FinancialStatementeEntriesCategoryData(
                            category_id = '', 
                            category_name = '', 
                            outcome = 1.337, 
                            subcategories = [
                                openapi_client.models.financial_statemente_entries_subcategory_data.FinancialStatementeEntriesSubcategoryData(
                                    subcategory_id = '', 
                                    subcategory_name = '', 
                                    outcome = 1.337, )
                                ], ), 
                        outflows_category_data = openapi_client.models.financial_statement_outlfows_category_data.FinancialStatementOutlfowsCategoryData(
                            category_id = '', 
                            category_name = '', 
                            outcome = 1.337, 
                            subcategories = [
                                openapi_client.models.financial_statement_outflows_subcategory_data.FinancialStatementOutflowsSubcategoryData(
                                    subcategory_id = '', 
                                    subcategory_name = '', 
                                    outcome = 1.337, )
                                ], ), 
                        outcome_data = openapi_client.models.financial_statement_outcome_report_data_entity.FinancialStatementOutcomeReportDataEntity(
                            name = '', 
                            outcome = 1.337, 
                            percentage = 1.337, ), )
                    ],
        )
        """

    def testFinancialStatementReport(self):
        """Test FinancialStatementReport"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
