# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 1.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from python_core_api_sdk.models.sync_bank_account_transactions_page_end_request_dto_legal_nature_assign_requests_inner import SyncBankAccountTransactionsPageEndRequestDtoLegalNatureAssignRequestsInner

class TestSyncBankAccountTransactionsPageEndRequestDtoLegalNatureAssignRequestsInner(unittest.TestCase):
    """SyncBankAccountTransactionsPageEndRequestDtoLegalNatureAssignRequestsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncBankAccountTransactionsPageEndRequestDtoLegalNatureAssignRequestsInner:
        """Test SyncBankAccountTransactionsPageEndRequestDtoLegalNatureAssignRequestsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncBankAccountTransactionsPageEndRequestDtoLegalNatureAssignRequestsInner`
        """
        model = SyncBankAccountTransactionsPageEndRequestDtoLegalNatureAssignRequestsInner()
        if include_optional:
            return SyncBankAccountTransactionsPageEndRequestDtoLegalNatureAssignRequestsInner(
                bank_provider_transaction_id = '',
                legal_nature = python_core_api_sdk.models.sync_bank_account_transactions_page_end_request_dto_legal_nature_assign_requests_inner_legal_nature.SyncBankAccountTransactionsPageEndRequestDto_legalNatureAssignRequests_inner_legalNature(
                    origin = 'AUTOMATIC', 
                    value = 'PERSONAL', 
                    prediction_response = python_core_api_sdk.models.create_or_update_bank_transactions_in_bulk_request_dto_items_inner_legal_nature_guesses_inner.CreateOrUpdateBankTransactionsInBulkRequestDto_items_inner_legalNatureGuesses_inner(
                        legal_nature = 'PERSONAL', 
                        confidence_score = 0, 
                        guesser_model_id = '', ), )
            )
        else:
            return SyncBankAccountTransactionsPageEndRequestDtoLegalNatureAssignRequestsInner(
                bank_provider_transaction_id = '',
                legal_nature = python_core_api_sdk.models.sync_bank_account_transactions_page_end_request_dto_legal_nature_assign_requests_inner_legal_nature.SyncBankAccountTransactionsPageEndRequestDto_legalNatureAssignRequests_inner_legalNature(
                    origin = 'AUTOMATIC', 
                    value = 'PERSONAL', 
                    prediction_response = python_core_api_sdk.models.create_or_update_bank_transactions_in_bulk_request_dto_items_inner_legal_nature_guesses_inner.CreateOrUpdateBankTransactionsInBulkRequestDto_items_inner_legalNatureGuesses_inner(
                        legal_nature = 'PERSONAL', 
                        confidence_score = 0, 
                        guesser_model_id = '', ), ),
        )
        """

    def testSyncBankAccountTransactionsPageEndRequestDtoLegalNatureAssignRequestsInner(self):
        """Test SyncBankAccountTransactionsPageEndRequestDtoLegalNatureAssignRequestsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
