# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 0.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.pluggy_api import PluggyApi


class TestPluggyApi(unittest.TestCase):
    """PluggyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PluggyApi()

    def tearDown(self) -> None:
        pass

    def test_pluggy_controller_create(self) -> None:
        """Test case for pluggy_controller_create

        """
        pass

    def test_pluggy_controller_webhook(self) -> None:
        """Test case for pluggy_controller_webhook

        """
        pass


if __name__ == '__main__':
    unittest.main()
