# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 0.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.plain_bank_account_entity import PlainBankAccountEntity

class TestPlainBankAccountEntity(unittest.TestCase):
    """PlainBankAccountEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlainBankAccountEntity:
        """Test PlainBankAccountEntity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlainBankAccountEntity`
        """
        model = PlainBankAccountEntity()
        if include_optional:
            return PlainBankAccountEntity(
                id = '',
                bank_connection_id = '',
                provider = '',
                provider_account_id = '',
                type = '',
                enabled = True,
                number = '',
                balance = 1.337,
                currency_code = '',
                name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PlainBankAccountEntity(
                id = '',
                bank_connection_id = '',
                provider = '',
                provider_account_id = '',
                type = '',
                enabled = True,
                number = '',
                balance = 1.337,
                currency_code = '',
                name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testPlainBankAccountEntity(self):
        """Test PlainBankAccountEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
