# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 1.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from python_core_api_sdk.models.user_entity_workspaces_inner_hybrid_settings import UserEntityWorkspacesInnerHybridSettings

class TestUserEntityWorkspacesInnerHybridSettings(unittest.TestCase):
    """UserEntityWorkspacesInnerHybridSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserEntityWorkspacesInnerHybridSettings:
        """Test UserEntityWorkspacesInnerHybridSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserEntityWorkspacesInnerHybridSettings`
        """
        model = UserEntityWorkspacesInnerHybridSettings()
        if include_optional:
            return UserEntityWorkspacesInnerHybridSettings(
                id = '',
                business_segment = 'ATTORNEY',
                other_business_description = ''
            )
        else:
            return UserEntityWorkspacesInnerHybridSettings(
                id = '',
                business_segment = 'ATTORNEY',
        )
        """

    def testUserEntityWorkspacesInnerHybridSettings(self):
        """Test UserEntityWorkspacesInnerHybridSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
