# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 0.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update_bank_transaction_request_dto import UpdateBankTransactionRequestDto

class TestUpdateBankTransactionRequestDto(unittest.TestCase):
    """UpdateBankTransactionRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateBankTransactionRequestDto:
        """Test UpdateBankTransactionRequestDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateBankTransactionRequestDto`
        """
        model = UpdateBankTransactionRequestDto()
        if include_optional:
            return UpdateBankTransactionRequestDto(
                description = '',
                category_id = '',
                competency_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ignore = True,
                confirm = True,
                tag_ids = [
                    ''
                    ],
                legal_nature = ''
            )
        else:
            return UpdateBankTransactionRequestDto(
        )
        """

    def testUpdateBankTransactionRequestDto(self):
        """Test UpdateBankTransactionRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
