# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 0.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_stripe_checkout_session_request_dto import CreateStripeCheckoutSessionRequestDto

class TestCreateStripeCheckoutSessionRequestDto(unittest.TestCase):
    """CreateStripeCheckoutSessionRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateStripeCheckoutSessionRequestDto:
        """Test CreateStripeCheckoutSessionRequestDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateStripeCheckoutSessionRequestDto`
        """
        model = CreateStripeCheckoutSessionRequestDto()
        if include_optional:
            return CreateStripeCheckoutSessionRequestDto(
                workspace_id = '',
                price_id = '',
                is_trial = True
            )
        else:
            return CreateStripeCheckoutSessionRequestDto(
                workspace_id = '',
                price_id = '',
                is_trial = True,
        )
        """

    def testCreateStripeCheckoutSessionRequestDto(self):
        """Test CreateStripeCheckoutSessionRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
