# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 0.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.profiles_api import ProfilesApi


class TestProfilesApi(unittest.TestCase):
    """ProfilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProfilesApi()

    def tearDown(self) -> None:
        pass

    def test_profiles_controller_create(self) -> None:
        """Test case for profiles_controller_create

        """
        pass

    def test_profiles_controller_get_my(self) -> None:
        """Test case for profiles_controller_get_my

        """
        pass

    def test_profiles_controller_parcial_update(self) -> None:
        """Test case for profiles_controller_parcial_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
