# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 1.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from python_core_api_sdk.models.create_or_update_bank_transactions_in_bulk_request_dto_items_inner_category_guesses_inner import CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCategoryGuessesInner

class TestCreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCategoryGuessesInner(unittest.TestCase):
    """CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCategoryGuessesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCategoryGuessesInner:
        """Test CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCategoryGuessesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCategoryGuessesInner`
        """
        model = CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCategoryGuessesInner()
        if include_optional:
            return CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCategoryGuessesInner(
                category_id = '',
                confidence_score = 0,
                guesser_model_id = ''
            )
        else:
            return CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCategoryGuessesInner(
                category_id = '',
                confidence_score = 0,
                guesser_model_id = '',
        )
        """

    def testCreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCategoryGuessesInner(self):
        """Test CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCategoryGuessesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
