# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 0.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.bank_transactions_api import BankTransactionsApi


class TestBankTransactionsApi(unittest.TestCase):
    """BankTransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BankTransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_bank_transactions_controller_create_or_update_bank_transactions_in_bulk(self) -> None:
        """Test case for bank_transactions_controller_create_or_update_bank_transactions_in_bulk

        """
        pass

    def test_bank_transactions_controller_get_bank_transactions(self) -> None:
        """Test case for bank_transactions_controller_get_bank_transactions

        """
        pass

    def test_bank_transactions_controller_get_bank_transactions_confirmed_today_by_me(self) -> None:
        """Test case for bank_transactions_controller_get_bank_transactions_confirmed_today_by_me

        """
        pass

    def test_bank_transactions_controller_get_bank_transactions_not_confirmed(self) -> None:
        """Test case for bank_transactions_controller_get_bank_transactions_not_confirmed

        """
        pass

    def test_bank_transactions_controller_get_bank_transactions_totals(self) -> None:
        """Test case for bank_transactions_controller_get_bank_transactions_totals

        """
        pass

    def test_bank_transactions_controller_get_recent(self) -> None:
        """Test case for bank_transactions_controller_get_recent

        """
        pass

    def test_bank_transactions_controller_get_transaction_details(self) -> None:
        """Test case for bank_transactions_controller_get_transaction_details

        """
        pass

    def test_bank_transactions_controller_update_transaction(self) -> None:
        """Test case for bank_transactions_controller_update_transaction

        """
        pass


if __name__ == '__main__':
    unittest.main()
