# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 0.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.stripe_api import StripeApi


class TestStripeApi(unittest.TestCase):
    """StripeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StripeApi()

    def tearDown(self) -> None:
        pass

    def test_stripe_controller_create_checkout_session_for_stripe(self) -> None:
        """Test case for stripe_controller_create_checkout_session_for_stripe

        """
        pass

    def test_stripe_controller_stripe_webhook(self) -> None:
        """Test case for stripe_controller_stripe_webhook

        """
        pass


if __name__ == '__main__':
    unittest.main()
