# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 1.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from python_core_api_sdk.models.sync_bank_account_transactions_request_dto import SyncBankAccountTransactionsRequestDto

class TestSyncBankAccountTransactionsRequestDto(unittest.TestCase):
    """SyncBankAccountTransactionsRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncBankAccountTransactionsRequestDto:
        """Test SyncBankAccountTransactionsRequestDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncBankAccountTransactionsRequestDto`
        """
        model = SyncBankAccountTransactionsRequestDto()
        if include_optional:
            return SyncBankAccountTransactionsRequestDto(
                account_id = '',
                provider = 'PLUGGY',
                provider_account_id = '',
                provider_item_id = ''
            )
        else:
            return SyncBankAccountTransactionsRequestDto(
                account_id = '',
                provider = 'PLUGGY',
                provider_account_id = '',
                provider_item_id = '',
        )
        """

    def testSyncBankAccountTransactionsRequestDto(self):
        """Test SyncBankAccountTransactionsRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
