# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 0.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.workspace_join_request_entity import WorkspaceJoinRequestEntity

class TestWorkspaceJoinRequestEntity(unittest.TestCase):
    """WorkspaceJoinRequestEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceJoinRequestEntity:
        """Test WorkspaceJoinRequestEntity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceJoinRequestEntity`
        """
        model = WorkspaceJoinRequestEntity()
        if include_optional:
            return WorkspaceJoinRequestEntity(
                id = '',
                status = '',
                workspace_id = '',
                user_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return WorkspaceJoinRequestEntity(
                id = '',
                status = '',
                workspace_id = '',
                user_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testWorkspaceJoinRequestEntity(self):
        """Test WorkspaceJoinRequestEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
