# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 0.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.message_tokens_api import MessageTokensApi


class TestMessageTokensApi(unittest.TestCase):
    """MessageTokensApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessageTokensApi()

    def tearDown(self) -> None:
        pass

    def test_message_tokens_controller_create_or_update_message_token(self) -> None:
        """Test case for message_tokens_controller_create_or_update_message_token

        """
        pass

    def test_message_tokens_controller_get_workspace_message_tokens(self) -> None:
        """Test case for message_tokens_controller_get_workspace_message_tokens

        """
        pass


if __name__ == '__main__':
    unittest.main()
