# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 1.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from python_core_api_sdk.api.bank_sync_api import BankSyncApi


class TestBankSyncApi(unittest.TestCase):
    """BankSyncApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BankSyncApi()

    def tearDown(self) -> None:
        pass

    def test_bank_sync_controller_sync_account_transactions(self) -> None:
        """Test case for bank_sync_controller_sync_account_transactions

        """
        pass

    def test_bank_sync_controller_sync_item(self) -> None:
        """Test case for bank_sync_controller_sync_item

        """
        pass

    def test_bank_sync_controller_sync_transactions_page_begin(self) -> None:
        """Test case for bank_sync_controller_sync_transactions_page_begin

        """
        pass

    def test_bank_sync_controller_sync_transactions_page_end(self) -> None:
        """Test case for bank_sync_controller_sync_transactions_page_end

        """
        pass


if __name__ == '__main__':
    unittest.main()
