# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 1.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from python_core_api_sdk.api.iam_workspaces_api import IamWorkspacesApi


class TestIamWorkspacesApi(unittest.TestCase):
    """IamWorkspacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IamWorkspacesApi()

    def tearDown(self) -> None:
        pass

    def test_workspaces_controller_create(self) -> None:
        """Test case for workspaces_controller_create

        """
        pass

    def test_workspaces_controller_parcial_update(self) -> None:
        """Test case for workspaces_controller_parcial_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
