# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 1.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from python_core_api_sdk.models.create_or_update_bank_transactions_in_bulk_request_dto_items_inner_credit_card_metadata import CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCreditCardMetadata

class TestCreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCreditCardMetadata(unittest.TestCase):
    """CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCreditCardMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCreditCardMetadata:
        """Test CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCreditCardMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCreditCardMetadata`
        """
        model = CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCreditCardMetadata()
        if include_optional:
            return CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCreditCardMetadata(
                installment_number = 1.337,
                total_installments = 1.337,
                total_amount = 1.337,
                payee_mcc = 1.337,
                card_number = '',
                bill_id = ''
            )
        else:
            return CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCreditCardMetadata(
        )
        """

    def testCreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCreditCardMetadata(self):
        """Test CreateOrUpdateBankTransactionsInBulkRequestDtoItemsInnerCreditCardMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
