# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 0.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.bank_connections_api import BankConnectionsApi


class TestBankConnectionsApi(unittest.TestCase):
    """BankConnectionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BankConnectionsApi()

    def tearDown(self) -> None:
        pass

    def test_bank_connections_controller_activate_bank_connection(self) -> None:
        """Test case for bank_connections_controller_activate_bank_connection

        """
        pass

    def test_bank_connections_controller_create_or_update_bank_connection(self) -> None:
        """Test case for bank_connections_controller_create_or_update_bank_connection

        """
        pass

    def test_bank_connections_controller_disable_bank_connection(self) -> None:
        """Test case for bank_connections_controller_disable_bank_connection

        """
        pass

    def test_bank_connections_controller_fetch_user_bank_connections(self) -> None:
        """Test case for bank_connections_controller_fetch_user_bank_connections

        """
        pass

    def test_bank_connections_controller_get_bank_connection_details(self) -> None:
        """Test case for bank_connections_controller_get_bank_connection_details

        """
        pass


if __name__ == '__main__':
    unittest.main()
