# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 0.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.bank_transaction_categories_api import BankTransactionCategoriesApi


class TestBankTransactionCategoriesApi(unittest.TestCase):
    """BankTransactionCategoriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BankTransactionCategoriesApi()

    def tearDown(self) -> None:
        pass

    def test_bank_transaction_categories_controller_get_bank_transaction_categories(self) -> None:
        """Test case for bank_transaction_categories_controller_get_bank_transaction_categories

        """
        pass


if __name__ == '__main__':
    unittest.main()
