# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 0.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_auth_controller_check_email_in_use(self) -> None:
        """Test case for auth_controller_check_email_in_use

        """
        pass

    def test_auth_controller_refresh(self) -> None:
        """Test case for auth_controller_refresh

        """
        pass

    def test_auth_controller_send_email_verification_code(self) -> None:
        """Test case for auth_controller_send_email_verification_code

        """
        pass

    def test_auth_controller_sign_in_with_email_password(self) -> None:
        """Test case for auth_controller_sign_in_with_email_password

        """
        pass

    def test_auth_controller_sign_up_with_email_password(self) -> None:
        """Test case for auth_controller_sign_up_with_email_password

        """
        pass


if __name__ == '__main__':
    unittest.main()
