# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 0.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_or_update_bank_account_request_dto import CreateOrUpdateBankAccountRequestDto

class TestCreateOrUpdateBankAccountRequestDto(unittest.TestCase):
    """CreateOrUpdateBankAccountRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrUpdateBankAccountRequestDto:
        """Test CreateOrUpdateBankAccountRequestDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrUpdateBankAccountRequestDto`
        """
        model = CreateOrUpdateBankAccountRequestDto()
        if include_optional:
            return CreateOrUpdateBankAccountRequestDto(
                bank_connection_id = '',
                provider = '',
                provider_account_id = '',
                type = '',
                number = '',
                balance = 1.337,
                currency_code = '',
                name = ''
            )
        else:
            return CreateOrUpdateBankAccountRequestDto(
                bank_connection_id = '',
                provider = '',
                provider_account_id = '',
                type = '',
                number = '',
                balance = 1.337,
                currency_code = '',
                name = '',
        )
        """

    def testCreateOrUpdateBankAccountRequestDto(self):
        """Test CreateOrUpdateBankAccountRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
