# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 1.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from python_core_api_sdk.models.sign_in_with_email_request_dto import SignInWithEmailRequestDto

class TestSignInWithEmailRequestDto(unittest.TestCase):
    """SignInWithEmailRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignInWithEmailRequestDto:
        """Test SignInWithEmailRequestDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignInWithEmailRequestDto`
        """
        model = SignInWithEmailRequestDto()
        if include_optional:
            return SignInWithEmailRequestDto(
                email = '',
                password = '012345',
                client_id = ''
            )
        else:
            return SignInWithEmailRequestDto(
                email = '',
                password = '012345',
                client_id = '',
        )
        """

    def testSignInWithEmailRequestDto(self):
        """Test SignInWithEmailRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
