# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 1.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from python_core_api_sdk.api.iam_auth_api import IamAuthApi


class TestIamAuthApi(unittest.TestCase):
    """IamAuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IamAuthApi()

    def tearDown(self) -> None:
        pass

    def test_auth_controller_generate_and_send_email_verification_code_for_sign_up(self) -> None:
        """Test case for auth_controller_generate_and_send_email_verification_code_for_sign_up

        """
        pass

    def test_auth_controller_generate_and_send_phone_verification_code_for_sign_up(self) -> None:
        """Test case for auth_controller_generate_and_send_phone_verification_code_for_sign_up

        """
        pass

    def test_auth_controller_sign_up_with_email_password(self) -> None:
        """Test case for auth_controller_sign_up_with_email_password

        """
        pass


if __name__ == '__main__':
    unittest.main()
