# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 0.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bank_connection_entity import BankConnectionEntity

class TestBankConnectionEntity(unittest.TestCase):
    """BankConnectionEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BankConnectionEntity:
        """Test BankConnectionEntity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BankConnectionEntity`
        """
        model = BankConnectionEntity()
        if include_optional:
            return BankConnectionEntity(
                id = '',
                created_by_user_id = '',
                workspace_id = '',
                enabled = True,
                provider = '',
                provider_item_id = '',
                history_range = '',
                connector_id = '',
                connector = openapi_client.models.bank_connector_entity.BankConnectorEntity(
                    id = '', 
                    provider = '', 
                    name = '', 
                    institution_url = '', 
                    image_url = '', 
                    primary_color = '', 
                    type = '', 
                    country = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return BankConnectionEntity(
                id = '',
                created_by_user_id = '',
                workspace_id = '',
                enabled = True,
                provider = '',
                provider_item_id = '',
                history_range = '',
                connector_id = '',
                connector = openapi_client.models.bank_connector_entity.BankConnectorEntity(
                    id = '', 
                    provider = '', 
                    name = '', 
                    institution_url = '', 
                    image_url = '', 
                    primary_color = '', 
                    type = '', 
                    country = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testBankConnectionEntity(self):
        """Test BankConnectionEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
