# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from python_core_api_sdk.models.base_model import Model
from python_core_api_sdk import util


class BankTransactionPaymentDataEntity(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, transaction_id: str=None, payeer_name: str=None, payer_branch_number: str=None, payer_account_number: str=None, payer_routing_number: str=None, payer_routing_number_ispb: str=None, payer_document_number_type: str=None, payer_document_number_value: str=None, reason: str=None, receiver_name: str=None, receiver_branch_number: str=None, receiver_account_number: str=None, receiver_routing_number: str=None, receiver_routing_number_ispb: str=None, receiver_document_number_type: str=None, receiver_document_number_value: str=None, payment_method: str=None, reference_number: str=None, receiver_reference_id: str=None, created_at: datetime=None, updated_at: datetime=None):
        """BankTransactionPaymentDataEntity - a model defined in OpenAPI

        :param id: The id of this BankTransactionPaymentDataEntity.
        :param transaction_id: The transaction_id of this BankTransactionPaymentDataEntity.
        :param payeer_name: The payeer_name of this BankTransactionPaymentDataEntity.
        :param payer_branch_number: The payer_branch_number of this BankTransactionPaymentDataEntity.
        :param payer_account_number: The payer_account_number of this BankTransactionPaymentDataEntity.
        :param payer_routing_number: The payer_routing_number of this BankTransactionPaymentDataEntity.
        :param payer_routing_number_ispb: The payer_routing_number_ispb of this BankTransactionPaymentDataEntity.
        :param payer_document_number_type: The payer_document_number_type of this BankTransactionPaymentDataEntity.
        :param payer_document_number_value: The payer_document_number_value of this BankTransactionPaymentDataEntity.
        :param reason: The reason of this BankTransactionPaymentDataEntity.
        :param receiver_name: The receiver_name of this BankTransactionPaymentDataEntity.
        :param receiver_branch_number: The receiver_branch_number of this BankTransactionPaymentDataEntity.
        :param receiver_account_number: The receiver_account_number of this BankTransactionPaymentDataEntity.
        :param receiver_routing_number: The receiver_routing_number of this BankTransactionPaymentDataEntity.
        :param receiver_routing_number_ispb: The receiver_routing_number_ispb of this BankTransactionPaymentDataEntity.
        :param receiver_document_number_type: The receiver_document_number_type of this BankTransactionPaymentDataEntity.
        :param receiver_document_number_value: The receiver_document_number_value of this BankTransactionPaymentDataEntity.
        :param payment_method: The payment_method of this BankTransactionPaymentDataEntity.
        :param reference_number: The reference_number of this BankTransactionPaymentDataEntity.
        :param receiver_reference_id: The receiver_reference_id of this BankTransactionPaymentDataEntity.
        :param created_at: The created_at of this BankTransactionPaymentDataEntity.
        :param updated_at: The updated_at of this BankTransactionPaymentDataEntity.
        """
        self.openapi_types = {
            'id': str,
            'transaction_id': str,
            'payeer_name': str,
            'payer_branch_number': str,
            'payer_account_number': str,
            'payer_routing_number': str,
            'payer_routing_number_ispb': str,
            'payer_document_number_type': str,
            'payer_document_number_value': str,
            'reason': str,
            'receiver_name': str,
            'receiver_branch_number': str,
            'receiver_account_number': str,
            'receiver_routing_number': str,
            'receiver_routing_number_ispb': str,
            'receiver_document_number_type': str,
            'receiver_document_number_value': str,
            'payment_method': str,
            'reference_number': str,
            'receiver_reference_id': str,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'transaction_id': 'transactionId',
            'payeer_name': 'payeerName',
            'payer_branch_number': 'payerBranchNumber',
            'payer_account_number': 'payerAccountNumber',
            'payer_routing_number': 'payerRoutingNumber',
            'payer_routing_number_ispb': 'payerRoutingNumberISPB',
            'payer_document_number_type': 'payerDocumentNumberType',
            'payer_document_number_value': 'payerDocumentNumberValue',
            'reason': 'reason',
            'receiver_name': 'receiverName',
            'receiver_branch_number': 'receiverBranchNumber',
            'receiver_account_number': 'receiverAccountNumber',
            'receiver_routing_number': 'receiverRoutingNumber',
            'receiver_routing_number_ispb': 'receiverRoutingNumberISPB',
            'receiver_document_number_type': 'receiverDocumentNumberType',
            'receiver_document_number_value': 'receiverDocumentNumberValue',
            'payment_method': 'paymentMethod',
            'reference_number': 'referenceNumber',
            'receiver_reference_id': 'receiverReferenceId',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }

        self._id = id
        self._transaction_id = transaction_id
        self._payeer_name = payeer_name
        self._payer_branch_number = payer_branch_number
        self._payer_account_number = payer_account_number
        self._payer_routing_number = payer_routing_number
        self._payer_routing_number_ispb = payer_routing_number_ispb
        self._payer_document_number_type = payer_document_number_type
        self._payer_document_number_value = payer_document_number_value
        self._reason = reason
        self._receiver_name = receiver_name
        self._receiver_branch_number = receiver_branch_number
        self._receiver_account_number = receiver_account_number
        self._receiver_routing_number = receiver_routing_number
        self._receiver_routing_number_ispb = receiver_routing_number_ispb
        self._receiver_document_number_type = receiver_document_number_type
        self._receiver_document_number_value = receiver_document_number_value
        self._payment_method = payment_method
        self._reference_number = reference_number
        self._receiver_reference_id = receiver_reference_id
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BankTransactionPaymentDataEntity':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The BankTransactionPaymentDataEntity of this BankTransactionPaymentDataEntity.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this BankTransactionPaymentDataEntity.


        :return: The id of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BankTransactionPaymentDataEntity.


        :param id: The id of this BankTransactionPaymentDataEntity.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def transaction_id(self):
        """Gets the transaction_id of this BankTransactionPaymentDataEntity.


        :return: The transaction_id of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._transaction_id

    @transaction_id.setter
    def transaction_id(self, transaction_id):
        """Sets the transaction_id of this BankTransactionPaymentDataEntity.


        :param transaction_id: The transaction_id of this BankTransactionPaymentDataEntity.
        :type transaction_id: str
        """
        if transaction_id is None:
            raise ValueError("Invalid value for `transaction_id`, must not be `None`")

        self._transaction_id = transaction_id

    @property
    def payeer_name(self):
        """Gets the payeer_name of this BankTransactionPaymentDataEntity.


        :return: The payeer_name of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._payeer_name

    @payeer_name.setter
    def payeer_name(self, payeer_name):
        """Sets the payeer_name of this BankTransactionPaymentDataEntity.


        :param payeer_name: The payeer_name of this BankTransactionPaymentDataEntity.
        :type payeer_name: str
        """

        self._payeer_name = payeer_name

    @property
    def payer_branch_number(self):
        """Gets the payer_branch_number of this BankTransactionPaymentDataEntity.


        :return: The payer_branch_number of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._payer_branch_number

    @payer_branch_number.setter
    def payer_branch_number(self, payer_branch_number):
        """Sets the payer_branch_number of this BankTransactionPaymentDataEntity.


        :param payer_branch_number: The payer_branch_number of this BankTransactionPaymentDataEntity.
        :type payer_branch_number: str
        """

        self._payer_branch_number = payer_branch_number

    @property
    def payer_account_number(self):
        """Gets the payer_account_number of this BankTransactionPaymentDataEntity.


        :return: The payer_account_number of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._payer_account_number

    @payer_account_number.setter
    def payer_account_number(self, payer_account_number):
        """Sets the payer_account_number of this BankTransactionPaymentDataEntity.


        :param payer_account_number: The payer_account_number of this BankTransactionPaymentDataEntity.
        :type payer_account_number: str
        """

        self._payer_account_number = payer_account_number

    @property
    def payer_routing_number(self):
        """Gets the payer_routing_number of this BankTransactionPaymentDataEntity.


        :return: The payer_routing_number of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._payer_routing_number

    @payer_routing_number.setter
    def payer_routing_number(self, payer_routing_number):
        """Sets the payer_routing_number of this BankTransactionPaymentDataEntity.


        :param payer_routing_number: The payer_routing_number of this BankTransactionPaymentDataEntity.
        :type payer_routing_number: str
        """

        self._payer_routing_number = payer_routing_number

    @property
    def payer_routing_number_ispb(self):
        """Gets the payer_routing_number_ispb of this BankTransactionPaymentDataEntity.


        :return: The payer_routing_number_ispb of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._payer_routing_number_ispb

    @payer_routing_number_ispb.setter
    def payer_routing_number_ispb(self, payer_routing_number_ispb):
        """Sets the payer_routing_number_ispb of this BankTransactionPaymentDataEntity.


        :param payer_routing_number_ispb: The payer_routing_number_ispb of this BankTransactionPaymentDataEntity.
        :type payer_routing_number_ispb: str
        """

        self._payer_routing_number_ispb = payer_routing_number_ispb

    @property
    def payer_document_number_type(self):
        """Gets the payer_document_number_type of this BankTransactionPaymentDataEntity.


        :return: The payer_document_number_type of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._payer_document_number_type

    @payer_document_number_type.setter
    def payer_document_number_type(self, payer_document_number_type):
        """Sets the payer_document_number_type of this BankTransactionPaymentDataEntity.


        :param payer_document_number_type: The payer_document_number_type of this BankTransactionPaymentDataEntity.
        :type payer_document_number_type: str
        """

        self._payer_document_number_type = payer_document_number_type

    @property
    def payer_document_number_value(self):
        """Gets the payer_document_number_value of this BankTransactionPaymentDataEntity.


        :return: The payer_document_number_value of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._payer_document_number_value

    @payer_document_number_value.setter
    def payer_document_number_value(self, payer_document_number_value):
        """Sets the payer_document_number_value of this BankTransactionPaymentDataEntity.


        :param payer_document_number_value: The payer_document_number_value of this BankTransactionPaymentDataEntity.
        :type payer_document_number_value: str
        """

        self._payer_document_number_value = payer_document_number_value

    @property
    def reason(self):
        """Gets the reason of this BankTransactionPaymentDataEntity.


        :return: The reason of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this BankTransactionPaymentDataEntity.


        :param reason: The reason of this BankTransactionPaymentDataEntity.
        :type reason: str
        """

        self._reason = reason

    @property
    def receiver_name(self):
        """Gets the receiver_name of this BankTransactionPaymentDataEntity.


        :return: The receiver_name of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._receiver_name

    @receiver_name.setter
    def receiver_name(self, receiver_name):
        """Sets the receiver_name of this BankTransactionPaymentDataEntity.


        :param receiver_name: The receiver_name of this BankTransactionPaymentDataEntity.
        :type receiver_name: str
        """

        self._receiver_name = receiver_name

    @property
    def receiver_branch_number(self):
        """Gets the receiver_branch_number of this BankTransactionPaymentDataEntity.


        :return: The receiver_branch_number of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._receiver_branch_number

    @receiver_branch_number.setter
    def receiver_branch_number(self, receiver_branch_number):
        """Sets the receiver_branch_number of this BankTransactionPaymentDataEntity.


        :param receiver_branch_number: The receiver_branch_number of this BankTransactionPaymentDataEntity.
        :type receiver_branch_number: str
        """

        self._receiver_branch_number = receiver_branch_number

    @property
    def receiver_account_number(self):
        """Gets the receiver_account_number of this BankTransactionPaymentDataEntity.


        :return: The receiver_account_number of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._receiver_account_number

    @receiver_account_number.setter
    def receiver_account_number(self, receiver_account_number):
        """Sets the receiver_account_number of this BankTransactionPaymentDataEntity.


        :param receiver_account_number: The receiver_account_number of this BankTransactionPaymentDataEntity.
        :type receiver_account_number: str
        """

        self._receiver_account_number = receiver_account_number

    @property
    def receiver_routing_number(self):
        """Gets the receiver_routing_number of this BankTransactionPaymentDataEntity.


        :return: The receiver_routing_number of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._receiver_routing_number

    @receiver_routing_number.setter
    def receiver_routing_number(self, receiver_routing_number):
        """Sets the receiver_routing_number of this BankTransactionPaymentDataEntity.


        :param receiver_routing_number: The receiver_routing_number of this BankTransactionPaymentDataEntity.
        :type receiver_routing_number: str
        """

        self._receiver_routing_number = receiver_routing_number

    @property
    def receiver_routing_number_ispb(self):
        """Gets the receiver_routing_number_ispb of this BankTransactionPaymentDataEntity.


        :return: The receiver_routing_number_ispb of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._receiver_routing_number_ispb

    @receiver_routing_number_ispb.setter
    def receiver_routing_number_ispb(self, receiver_routing_number_ispb):
        """Sets the receiver_routing_number_ispb of this BankTransactionPaymentDataEntity.


        :param receiver_routing_number_ispb: The receiver_routing_number_ispb of this BankTransactionPaymentDataEntity.
        :type receiver_routing_number_ispb: str
        """

        self._receiver_routing_number_ispb = receiver_routing_number_ispb

    @property
    def receiver_document_number_type(self):
        """Gets the receiver_document_number_type of this BankTransactionPaymentDataEntity.


        :return: The receiver_document_number_type of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._receiver_document_number_type

    @receiver_document_number_type.setter
    def receiver_document_number_type(self, receiver_document_number_type):
        """Sets the receiver_document_number_type of this BankTransactionPaymentDataEntity.


        :param receiver_document_number_type: The receiver_document_number_type of this BankTransactionPaymentDataEntity.
        :type receiver_document_number_type: str
        """

        self._receiver_document_number_type = receiver_document_number_type

    @property
    def receiver_document_number_value(self):
        """Gets the receiver_document_number_value of this BankTransactionPaymentDataEntity.


        :return: The receiver_document_number_value of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._receiver_document_number_value

    @receiver_document_number_value.setter
    def receiver_document_number_value(self, receiver_document_number_value):
        """Sets the receiver_document_number_value of this BankTransactionPaymentDataEntity.


        :param receiver_document_number_value: The receiver_document_number_value of this BankTransactionPaymentDataEntity.
        :type receiver_document_number_value: str
        """

        self._receiver_document_number_value = receiver_document_number_value

    @property
    def payment_method(self):
        """Gets the payment_method of this BankTransactionPaymentDataEntity.


        :return: The payment_method of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._payment_method

    @payment_method.setter
    def payment_method(self, payment_method):
        """Sets the payment_method of this BankTransactionPaymentDataEntity.


        :param payment_method: The payment_method of this BankTransactionPaymentDataEntity.
        :type payment_method: str
        """

        self._payment_method = payment_method

    @property
    def reference_number(self):
        """Gets the reference_number of this BankTransactionPaymentDataEntity.


        :return: The reference_number of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._reference_number

    @reference_number.setter
    def reference_number(self, reference_number):
        """Sets the reference_number of this BankTransactionPaymentDataEntity.


        :param reference_number: The reference_number of this BankTransactionPaymentDataEntity.
        :type reference_number: str
        """

        self._reference_number = reference_number

    @property
    def receiver_reference_id(self):
        """Gets the receiver_reference_id of this BankTransactionPaymentDataEntity.


        :return: The receiver_reference_id of this BankTransactionPaymentDataEntity.
        :rtype: str
        """
        return self._receiver_reference_id

    @receiver_reference_id.setter
    def receiver_reference_id(self, receiver_reference_id):
        """Sets the receiver_reference_id of this BankTransactionPaymentDataEntity.


        :param receiver_reference_id: The receiver_reference_id of this BankTransactionPaymentDataEntity.
        :type receiver_reference_id: str
        """

        self._receiver_reference_id = receiver_reference_id

    @property
    def created_at(self):
        """Gets the created_at of this BankTransactionPaymentDataEntity.


        :return: The created_at of this BankTransactionPaymentDataEntity.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this BankTransactionPaymentDataEntity.


        :param created_at: The created_at of this BankTransactionPaymentDataEntity.
        :type created_at: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this BankTransactionPaymentDataEntity.


        :return: The updated_at of this BankTransactionPaymentDataEntity.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this BankTransactionPaymentDataEntity.


        :param updated_at: The updated_at of this BankTransactionPaymentDataEntity.
        :type updated_at: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")

        self._updated_at = updated_at
