# coding: utf-8

"""
    Sofia Api

    Api principal do sistema Sofia.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from python_core_api_sdk.models.bank_transaction_category_plain_entity import BankTransactionCategoryPlainEntity
from typing import Optional, Set
from typing_extensions import Self

class BankTransactionCategoryEntity(BaseModel):
    """
    BankTransactionCategoryEntity
    """ # noqa: E501
    id: StrictStr
    name: StrictStr
    nature: StrictStr
    parent_id: Optional[StrictStr] = Field(default=None, alias="parentId")
    path: List[BankTransactionCategoryPlainEntity]
    children: List[BankTransactionCategoryPlainEntity]
    __properties: ClassVar[List[str]] = ["id", "name", "nature", "parentId", "path", "children"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BankTransactionCategoryEntity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in path (list)
        _items = []
        if self.path:
            for _item in self.path:
                if _item:
                    _items.append(_item.to_dict())
            _dict['path'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in children (list)
        _items = []
        if self.children:
            for _item in self.children:
                if _item:
                    _items.append(_item.to_dict())
            _dict['children'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BankTransactionCategoryEntity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "nature": obj.get("nature"),
            "parentId": obj.get("parentId"),
            "path": [BankTransactionCategoryPlainEntity.from_dict(_item) for _item in obj["path"]] if obj.get("path") is not None else None,
            "children": [BankTransactionCategoryPlainEntity.from_dict(_item) for _item in obj["children"]] if obj.get("children") is not None else None
        })
        return _obj


