# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from python_core_api_sdk.models.base_model import Model
from python_core_api_sdk import util


class BankTransactionCategoryPlainEntity(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, nature: str=None, parent_id: str=None):
        """BankTransactionCategoryPlainEntity - a model defined in OpenAPI

        :param id: The id of this BankTransactionCategoryPlainEntity.
        :param name: The name of this BankTransactionCategoryPlainEntity.
        :param nature: The nature of this BankTransactionCategoryPlainEntity.
        :param parent_id: The parent_id of this BankTransactionCategoryPlainEntity.
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'nature': str,
            'parent_id': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'nature': 'nature',
            'parent_id': 'parentId'
        }

        self._id = id
        self._name = name
        self._nature = nature
        self._parent_id = parent_id

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BankTransactionCategoryPlainEntity':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The BankTransactionCategoryPlainEntity of this BankTransactionCategoryPlainEntity.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this BankTransactionCategoryPlainEntity.


        :return: The id of this BankTransactionCategoryPlainEntity.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BankTransactionCategoryPlainEntity.


        :param id: The id of this BankTransactionCategoryPlainEntity.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def name(self):
        """Gets the name of this BankTransactionCategoryPlainEntity.


        :return: The name of this BankTransactionCategoryPlainEntity.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BankTransactionCategoryPlainEntity.


        :param name: The name of this BankTransactionCategoryPlainEntity.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def nature(self):
        """Gets the nature of this BankTransactionCategoryPlainEntity.


        :return: The nature of this BankTransactionCategoryPlainEntity.
        :rtype: str
        """
        return self._nature

    @nature.setter
    def nature(self, nature):
        """Sets the nature of this BankTransactionCategoryPlainEntity.


        :param nature: The nature of this BankTransactionCategoryPlainEntity.
        :type nature: str
        """
        if nature is None:
            raise ValueError("Invalid value for `nature`, must not be `None`")

        self._nature = nature

    @property
    def parent_id(self):
        """Gets the parent_id of this BankTransactionCategoryPlainEntity.


        :return: The parent_id of this BankTransactionCategoryPlainEntity.
        :rtype: str
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id):
        """Sets the parent_id of this BankTransactionCategoryPlainEntity.


        :param parent_id: The parent_id of this BankTransactionCategoryPlainEntity.
        :type parent_id: str
        """

        self._parent_id = parent_id
