# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from python_core_api_sdk.models.base_model import Model
from python_core_api_sdk import util


class CashFlowReportDailyItemEntity(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, index: float=None, _date: datetime=None, day_of_year: float=None, label: str=None, min_date: datetime=None, max_date: datetime=None, value: float=None):
        """CashFlowReportDailyItemEntity - a model defined in OpenAPI

        :param index: The index of this CashFlowReportDailyItemEntity.
        :param _date: The _date of this CashFlowReportDailyItemEntity.
        :param day_of_year: The day_of_year of this CashFlowReportDailyItemEntity.
        :param label: The label of this CashFlowReportDailyItemEntity.
        :param min_date: The min_date of this CashFlowReportDailyItemEntity.
        :param max_date: The max_date of this CashFlowReportDailyItemEntity.
        :param value: The value of this CashFlowReportDailyItemEntity.
        """
        self.openapi_types = {
            'index': float,
            '_date': datetime,
            'day_of_year': float,
            'label': str,
            'min_date': datetime,
            'max_date': datetime,
            'value': float
        }

        self.attribute_map = {
            'index': 'index',
            '_date': 'date',
            'day_of_year': 'dayOfYear',
            'label': 'label',
            'min_date': 'minDate',
            'max_date': 'maxDate',
            'value': 'value'
        }

        self._index = index
        self.__date = _date
        self._day_of_year = day_of_year
        self._label = label
        self._min_date = min_date
        self._max_date = max_date
        self._value = value

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CashFlowReportDailyItemEntity':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CashFlowReportDailyItemEntity of this CashFlowReportDailyItemEntity.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def index(self):
        """Gets the index of this CashFlowReportDailyItemEntity.


        :return: The index of this CashFlowReportDailyItemEntity.
        :rtype: float
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this CashFlowReportDailyItemEntity.


        :param index: The index of this CashFlowReportDailyItemEntity.
        :type index: float
        """
        if index is None:
            raise ValueError("Invalid value for `index`, must not be `None`")

        self._index = index

    @property
    def _date(self):
        """Gets the _date of this CashFlowReportDailyItemEntity.


        :return: The _date of this CashFlowReportDailyItemEntity.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this CashFlowReportDailyItemEntity.


        :param _date: The _date of this CashFlowReportDailyItemEntity.
        :type _date: datetime
        """
        if _date is None:
            raise ValueError("Invalid value for `_date`, must not be `None`")

        self.__date = _date

    @property
    def day_of_year(self):
        """Gets the day_of_year of this CashFlowReportDailyItemEntity.


        :return: The day_of_year of this CashFlowReportDailyItemEntity.
        :rtype: float
        """
        return self._day_of_year

    @day_of_year.setter
    def day_of_year(self, day_of_year):
        """Sets the day_of_year of this CashFlowReportDailyItemEntity.


        :param day_of_year: The day_of_year of this CashFlowReportDailyItemEntity.
        :type day_of_year: float
        """
        if day_of_year is None:
            raise ValueError("Invalid value for `day_of_year`, must not be `None`")

        self._day_of_year = day_of_year

    @property
    def label(self):
        """Gets the label of this CashFlowReportDailyItemEntity.


        :return: The label of this CashFlowReportDailyItemEntity.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this CashFlowReportDailyItemEntity.


        :param label: The label of this CashFlowReportDailyItemEntity.
        :type label: str
        """
        if label is None:
            raise ValueError("Invalid value for `label`, must not be `None`")

        self._label = label

    @property
    def min_date(self):
        """Gets the min_date of this CashFlowReportDailyItemEntity.


        :return: The min_date of this CashFlowReportDailyItemEntity.
        :rtype: datetime
        """
        return self._min_date

    @min_date.setter
    def min_date(self, min_date):
        """Sets the min_date of this CashFlowReportDailyItemEntity.


        :param min_date: The min_date of this CashFlowReportDailyItemEntity.
        :type min_date: datetime
        """
        if min_date is None:
            raise ValueError("Invalid value for `min_date`, must not be `None`")

        self._min_date = min_date

    @property
    def max_date(self):
        """Gets the max_date of this CashFlowReportDailyItemEntity.


        :return: The max_date of this CashFlowReportDailyItemEntity.
        :rtype: datetime
        """
        return self._max_date

    @max_date.setter
    def max_date(self, max_date):
        """Sets the max_date of this CashFlowReportDailyItemEntity.


        :param max_date: The max_date of this CashFlowReportDailyItemEntity.
        :type max_date: datetime
        """
        if max_date is None:
            raise ValueError("Invalid value for `max_date`, must not be `None`")

        self._max_date = max_date

    @property
    def value(self):
        """Gets the value of this CashFlowReportDailyItemEntity.


        :return: The value of this CashFlowReportDailyItemEntity.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this CashFlowReportDailyItemEntity.


        :param value: The value of this CashFlowReportDailyItemEntity.
        :type value: float
        """

        self._value = value
