# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from python_core_api_sdk.models.base_model import Model
from python_core_api_sdk import util


class CashFlowReportWeeklyItemEntity(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, index: float=None, _date: datetime=None, week: float=None, label: str=None, min_date: datetime=None, max_date: datetime=None, value: float=None):
        """CashFlowReportWeeklyItemEntity - a model defined in OpenAPI

        :param index: The index of this CashFlowReportWeeklyItemEntity.
        :param _date: The _date of this CashFlowReportWeeklyItemEntity.
        :param week: The week of this CashFlowReportWeeklyItemEntity.
        :param label: The label of this CashFlowReportWeeklyItemEntity.
        :param min_date: The min_date of this CashFlowReportWeeklyItemEntity.
        :param max_date: The max_date of this CashFlowReportWeeklyItemEntity.
        :param value: The value of this CashFlowReportWeeklyItemEntity.
        """
        self.openapi_types = {
            'index': float,
            '_date': datetime,
            'week': float,
            'label': str,
            'min_date': datetime,
            'max_date': datetime,
            'value': float
        }

        self.attribute_map = {
            'index': 'index',
            '_date': 'date',
            'week': 'week',
            'label': 'label',
            'min_date': 'minDate',
            'max_date': 'maxDate',
            'value': 'value'
        }

        self._index = index
        self.__date = _date
        self._week = week
        self._label = label
        self._min_date = min_date
        self._max_date = max_date
        self._value = value

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CashFlowReportWeeklyItemEntity':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CashFlowReportWeeklyItemEntity of this CashFlowReportWeeklyItemEntity.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def index(self):
        """Gets the index of this CashFlowReportWeeklyItemEntity.


        :return: The index of this CashFlowReportWeeklyItemEntity.
        :rtype: float
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this CashFlowReportWeeklyItemEntity.


        :param index: The index of this CashFlowReportWeeklyItemEntity.
        :type index: float
        """
        if index is None:
            raise ValueError("Invalid value for `index`, must not be `None`")

        self._index = index

    @property
    def _date(self):
        """Gets the _date of this CashFlowReportWeeklyItemEntity.


        :return: The _date of this CashFlowReportWeeklyItemEntity.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this CashFlowReportWeeklyItemEntity.


        :param _date: The _date of this CashFlowReportWeeklyItemEntity.
        :type _date: datetime
        """
        if _date is None:
            raise ValueError("Invalid value for `_date`, must not be `None`")

        self.__date = _date

    @property
    def week(self):
        """Gets the week of this CashFlowReportWeeklyItemEntity.


        :return: The week of this CashFlowReportWeeklyItemEntity.
        :rtype: float
        """
        return self._week

    @week.setter
    def week(self, week):
        """Sets the week of this CashFlowReportWeeklyItemEntity.


        :param week: The week of this CashFlowReportWeeklyItemEntity.
        :type week: float
        """
        if week is None:
            raise ValueError("Invalid value for `week`, must not be `None`")

        self._week = week

    @property
    def label(self):
        """Gets the label of this CashFlowReportWeeklyItemEntity.


        :return: The label of this CashFlowReportWeeklyItemEntity.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this CashFlowReportWeeklyItemEntity.


        :param label: The label of this CashFlowReportWeeklyItemEntity.
        :type label: str
        """
        if label is None:
            raise ValueError("Invalid value for `label`, must not be `None`")

        self._label = label

    @property
    def min_date(self):
        """Gets the min_date of this CashFlowReportWeeklyItemEntity.


        :return: The min_date of this CashFlowReportWeeklyItemEntity.
        :rtype: datetime
        """
        return self._min_date

    @min_date.setter
    def min_date(self, min_date):
        """Sets the min_date of this CashFlowReportWeeklyItemEntity.


        :param min_date: The min_date of this CashFlowReportWeeklyItemEntity.
        :type min_date: datetime
        """
        if min_date is None:
            raise ValueError("Invalid value for `min_date`, must not be `None`")

        self._min_date = min_date

    @property
    def max_date(self):
        """Gets the max_date of this CashFlowReportWeeklyItemEntity.


        :return: The max_date of this CashFlowReportWeeklyItemEntity.
        :rtype: datetime
        """
        return self._max_date

    @max_date.setter
    def max_date(self, max_date):
        """Sets the max_date of this CashFlowReportWeeklyItemEntity.


        :param max_date: The max_date of this CashFlowReportWeeklyItemEntity.
        :type max_date: datetime
        """
        if max_date is None:
            raise ValueError("Invalid value for `max_date`, must not be `None`")

        self._max_date = max_date

    @property
    def value(self):
        """Gets the value of this CashFlowReportWeeklyItemEntity.


        :return: The value of this CashFlowReportWeeklyItemEntity.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this CashFlowReportWeeklyItemEntity.


        :param value: The value of this CashFlowReportWeeklyItemEntity.
        :type value: float
        """

        self._value = value
