# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from python_core_api_sdk.models.base_model import Model
from python_core_api_sdk import util


class CreatePluggyConnectTokenRequestDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, item_id: str=None, workspace_id: str=None, history_range: str=None):
        """CreatePluggyConnectTokenRequestDto - a model defined in OpenAPI

        :param item_id: The item_id of this CreatePluggyConnectTokenRequestDto.
        :param workspace_id: The workspace_id of this CreatePluggyConnectTokenRequestDto.
        :param history_range: The history_range of this CreatePluggyConnectTokenRequestDto.
        """
        self.openapi_types = {
            'item_id': str,
            'workspace_id': str,
            'history_range': str
        }

        self.attribute_map = {
            'item_id': 'itemId',
            'workspace_id': 'workspaceId',
            'history_range': 'historyRange'
        }

        self._item_id = item_id
        self._workspace_id = workspace_id
        self._history_range = history_range

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CreatePluggyConnectTokenRequestDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CreatePluggyConnectTokenRequestDto of this CreatePluggyConnectTokenRequestDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def item_id(self):
        """Gets the item_id of this CreatePluggyConnectTokenRequestDto.


        :return: The item_id of this CreatePluggyConnectTokenRequestDto.
        :rtype: str
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id):
        """Sets the item_id of this CreatePluggyConnectTokenRequestDto.


        :param item_id: The item_id of this CreatePluggyConnectTokenRequestDto.
        :type item_id: str
        """

        self._item_id = item_id

    @property
    def workspace_id(self):
        """Gets the workspace_id of this CreatePluggyConnectTokenRequestDto.


        :return: The workspace_id of this CreatePluggyConnectTokenRequestDto.
        :rtype: str
        """
        return self._workspace_id

    @workspace_id.setter
    def workspace_id(self, workspace_id):
        """Sets the workspace_id of this CreatePluggyConnectTokenRequestDto.


        :param workspace_id: The workspace_id of this CreatePluggyConnectTokenRequestDto.
        :type workspace_id: str
        """
        if workspace_id is None:
            raise ValueError("Invalid value for `workspace_id`, must not be `None`")

        self._workspace_id = workspace_id

    @property
    def history_range(self):
        """Gets the history_range of this CreatePluggyConnectTokenRequestDto.


        :return: The history_range of this CreatePluggyConnectTokenRequestDto.
        :rtype: str
        """
        return self._history_range

    @history_range.setter
    def history_range(self, history_range):
        """Sets the history_range of this CreatePluggyConnectTokenRequestDto.


        :param history_range: The history_range of this CreatePluggyConnectTokenRequestDto.
        :type history_range: str
        """
        if history_range is None:
            raise ValueError("Invalid value for `history_range`, must not be `None`")

        self._history_range = history_range
