# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from python_core_api_sdk.models.base_model import Model
from python_core_api_sdk.models.create_or_update_bank_transactions_in_bulk_item_dto import CreateOrUpdateBankTransactionsInBulkItemDto
from python_core_api_sdk import util


class CreateOrUpdateBankTransactionsInBulkRequestDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items: List[CreateOrUpdateBankTransactionsInBulkItemDto]=None):
        """CreateOrUpdateBankTransactionsInBulkRequestDto - a model defined in OpenAPI

        :param items: The items of this CreateOrUpdateBankTransactionsInBulkRequestDto.
        """
        self.openapi_types = {
            'items': List[CreateOrUpdateBankTransactionsInBulkItemDto]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CreateOrUpdateBankTransactionsInBulkRequestDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CreateOrUpdateBankTransactionsInBulkRequestDto of this CreateOrUpdateBankTransactionsInBulkRequestDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self):
        """Gets the items of this CreateOrUpdateBankTransactionsInBulkRequestDto.


        :return: The items of this CreateOrUpdateBankTransactionsInBulkRequestDto.
        :rtype: List[CreateOrUpdateBankTransactionsInBulkItemDto]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this CreateOrUpdateBankTransactionsInBulkRequestDto.


        :param items: The items of this CreateOrUpdateBankTransactionsInBulkRequestDto.
        :type items: List[CreateOrUpdateBankTransactionsInBulkItemDto]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")

        self._items = items
