# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from python_core_api_sdk.models.base_model import Model
from python_core_api_sdk.models.financial_statement_report_item_entity import FinancialStatementReportItemEntity
from python_core_api_sdk import util


class FinancialStatementReport(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items: List[FinancialStatementReportItemEntity]=None):
        """FinancialStatementReport - a model defined in OpenAPI

        :param items: The items of this FinancialStatementReport.
        """
        self.openapi_types = {
            'items': List[FinancialStatementReportItemEntity]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt: dict) -> 'FinancialStatementReport':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The FinancialStatementReport of this FinancialStatementReport.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self):
        """Gets the items of this FinancialStatementReport.


        :return: The items of this FinancialStatementReport.
        :rtype: List[FinancialStatementReportItemEntity]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this FinancialStatementReport.


        :param items: The items of this FinancialStatementReport.
        :type items: List[FinancialStatementReportItemEntity]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")

        self._items = items
