# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from python_core_api_sdk.models.base_model import Model
from python_core_api_sdk.models.payments_manager_product_price_entity import PaymentsManagerProductPriceEntity
from python_core_api_sdk import util


class PaymentsManagerProductDataEntity(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, description: str=None, prices: List[PaymentsManagerProductPriceEntity]=None):
        """PaymentsManagerProductDataEntity - a model defined in OpenAPI

        :param id: The id of this PaymentsManagerProductDataEntity.
        :param name: The name of this PaymentsManagerProductDataEntity.
        :param description: The description of this PaymentsManagerProductDataEntity.
        :param prices: The prices of this PaymentsManagerProductDataEntity.
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'description': str,
            'prices': List[PaymentsManagerProductPriceEntity]
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'prices': 'prices'
        }

        self._id = id
        self._name = name
        self._description = description
        self._prices = prices

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PaymentsManagerProductDataEntity':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The PaymentsManagerProductDataEntity of this PaymentsManagerProductDataEntity.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this PaymentsManagerProductDataEntity.


        :return: The id of this PaymentsManagerProductDataEntity.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PaymentsManagerProductDataEntity.


        :param id: The id of this PaymentsManagerProductDataEntity.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def name(self):
        """Gets the name of this PaymentsManagerProductDataEntity.


        :return: The name of this PaymentsManagerProductDataEntity.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PaymentsManagerProductDataEntity.


        :param name: The name of this PaymentsManagerProductDataEntity.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def description(self):
        """Gets the description of this PaymentsManagerProductDataEntity.


        :return: The description of this PaymentsManagerProductDataEntity.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PaymentsManagerProductDataEntity.


        :param description: The description of this PaymentsManagerProductDataEntity.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")

        self._description = description

    @property
    def prices(self):
        """Gets the prices of this PaymentsManagerProductDataEntity.


        :return: The prices of this PaymentsManagerProductDataEntity.
        :rtype: List[PaymentsManagerProductPriceEntity]
        """
        return self._prices

    @prices.setter
    def prices(self, prices):
        """Sets the prices of this PaymentsManagerProductDataEntity.


        :param prices: The prices of this PaymentsManagerProductDataEntity.
        :type prices: List[PaymentsManagerProductPriceEntity]
        """
        if prices is None:
            raise ValueError("Invalid value for `prices`, must not be `None`")

        self._prices = prices
