# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from python_core_api_sdk.models.base_model import Model
from python_core_api_sdk import util


class WorkspaceEntity(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, pretty_id: str=None, name: str=None, type: str=None, creator_user_id: str=None, created_at: datetime=None, selected_personal_category_tree_id: str=None, selected_business_category_tree_id: str=None):
        """WorkspaceEntity - a model defined in OpenAPI

        :param id: The id of this WorkspaceEntity.
        :param pretty_id: The pretty_id of this WorkspaceEntity.
        :param name: The name of this WorkspaceEntity.
        :param type: The type of this WorkspaceEntity.
        :param creator_user_id: The creator_user_id of this WorkspaceEntity.
        :param created_at: The created_at of this WorkspaceEntity.
        :param selected_personal_category_tree_id: The selected_personal_category_tree_id of this WorkspaceEntity.
        :param selected_business_category_tree_id: The selected_business_category_tree_id of this WorkspaceEntity.
        """
        self.openapi_types = {
            'id': str,
            'pretty_id': str,
            'name': str,
            'type': str,
            'creator_user_id': str,
            'created_at': datetime,
            'selected_personal_category_tree_id': str,
            'selected_business_category_tree_id': str
        }

        self.attribute_map = {
            'id': 'id',
            'pretty_id': 'prettyId',
            'name': 'name',
            'type': 'type',
            'creator_user_id': 'creatorUserId',
            'created_at': 'createdAt',
            'selected_personal_category_tree_id': 'selectedPersonalCategoryTreeId',
            'selected_business_category_tree_id': 'selectedBusinessCategoryTreeId'
        }

        self._id = id
        self._pretty_id = pretty_id
        self._name = name
        self._type = type
        self._creator_user_id = creator_user_id
        self._created_at = created_at
        self._selected_personal_category_tree_id = selected_personal_category_tree_id
        self._selected_business_category_tree_id = selected_business_category_tree_id

    @classmethod
    def from_dict(cls, dikt: dict) -> 'WorkspaceEntity':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The WorkspaceEntity of this WorkspaceEntity.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this WorkspaceEntity.


        :return: The id of this WorkspaceEntity.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WorkspaceEntity.


        :param id: The id of this WorkspaceEntity.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def pretty_id(self):
        """Gets the pretty_id of this WorkspaceEntity.


        :return: The pretty_id of this WorkspaceEntity.
        :rtype: str
        """
        return self._pretty_id

    @pretty_id.setter
    def pretty_id(self, pretty_id):
        """Sets the pretty_id of this WorkspaceEntity.


        :param pretty_id: The pretty_id of this WorkspaceEntity.
        :type pretty_id: str
        """
        if pretty_id is None:
            raise ValueError("Invalid value for `pretty_id`, must not be `None`")

        self._pretty_id = pretty_id

    @property
    def name(self):
        """Gets the name of this WorkspaceEntity.


        :return: The name of this WorkspaceEntity.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WorkspaceEntity.


        :param name: The name of this WorkspaceEntity.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def type(self):
        """Gets the type of this WorkspaceEntity.


        :return: The type of this WorkspaceEntity.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this WorkspaceEntity.


        :param type: The type of this WorkspaceEntity.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def creator_user_id(self):
        """Gets the creator_user_id of this WorkspaceEntity.


        :return: The creator_user_id of this WorkspaceEntity.
        :rtype: str
        """
        return self._creator_user_id

    @creator_user_id.setter
    def creator_user_id(self, creator_user_id):
        """Sets the creator_user_id of this WorkspaceEntity.


        :param creator_user_id: The creator_user_id of this WorkspaceEntity.
        :type creator_user_id: str
        """
        if creator_user_id is None:
            raise ValueError("Invalid value for `creator_user_id`, must not be `None`")

        self._creator_user_id = creator_user_id

    @property
    def created_at(self):
        """Gets the created_at of this WorkspaceEntity.


        :return: The created_at of this WorkspaceEntity.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this WorkspaceEntity.


        :param created_at: The created_at of this WorkspaceEntity.
        :type created_at: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")

        self._created_at = created_at

    @property
    def selected_personal_category_tree_id(self):
        """Gets the selected_personal_category_tree_id of this WorkspaceEntity.


        :return: The selected_personal_category_tree_id of this WorkspaceEntity.
        :rtype: str
        """
        return self._selected_personal_category_tree_id

    @selected_personal_category_tree_id.setter
    def selected_personal_category_tree_id(self, selected_personal_category_tree_id):
        """Sets the selected_personal_category_tree_id of this WorkspaceEntity.


        :param selected_personal_category_tree_id: The selected_personal_category_tree_id of this WorkspaceEntity.
        :type selected_personal_category_tree_id: str
        """

        self._selected_personal_category_tree_id = selected_personal_category_tree_id

    @property
    def selected_business_category_tree_id(self):
        """Gets the selected_business_category_tree_id of this WorkspaceEntity.


        :return: The selected_business_category_tree_id of this WorkspaceEntity.
        :rtype: str
        """
        return self._selected_business_category_tree_id

    @selected_business_category_tree_id.setter
    def selected_business_category_tree_id(self, selected_business_category_tree_id):
        """Sets the selected_business_category_tree_id of this WorkspaceEntity.


        :param selected_business_category_tree_id: The selected_business_category_tree_id of this WorkspaceEntity.
        :type selected_business_category_tree_id: str
        """

        self._selected_business_category_tree_id = selected_business_category_tree_id
